CloudSlang/CloudSlang.github.io

index.js, package.json
@dorsha please review and merge
=> added compression

app/scripts/controllers/main.js
=> Added blog

app/views/codesnippets/sprintcontextcode.html
=> fixed typo

.gitignore, app/markdowns/slang.md
Signed-off-by: Avi Moradi <avi.moradi@hp.com>
=> rename & invert override to overridable

app/markdowns/developer.md, app/markdowns/slang.md
=> changes for toc sidebar

app/markdowns/developer.md, app/markdowns/slang.md
=> updated code samples as per #51

app/markdowns/score.md, app/markdowns/slang.md
=> changes for new cli and sidebar

app/markdowns/score.md, app/markdowns/slang.md, app/views/downloadclibox.html
=> changed cli download links to 0.7.4 as per #45

app/scripts/controllers/main.js, app/scripts/services/messages.js, app/styles/main.css, app/views/footer.html, app/views/navbar.html
Signed-off-by: Eliya Sadan <eliyasadan@gmail.com>
=> community section

app/markdowns/slang.md
Fixes #69. Fixes #70. Fixes #72. Fixes #73.
=> Bughunt fixes

app/index.html
=> fix site title and description

app/markdowns/developer.md, app/markdowns/slang.md
fixes issues found by @einatneu
=> more typos, capitalization, etc

app/markdowns/slang.md
Fixes CloudSlang/cloud-slang#225
=> added examples for some of the run commands

app/markdowns/slang.md, app/slang-content/examples/async/async_loop_aggregate.sl, app/slang-content/examples/async/print_branch.sl
=> added async_loop to docs

app/index.html
add Docker and "Orchestration as Code" as meta name
=> Update index - add meta names

app/markdowns/slang.md
=> removed mention of break

app/views/docs.html
=> change video link

app/markdowns/slang.md
=> updated --cp behavior

app/markdowns/overview.md
=> beefed up the overview section

app/markdowns/slang.md
=> added instructions for skipped default tests

app/markdowns/slang.md
=> added build tool coverage flag

app/markdowns/overview.md
=> aligned run command to new structure

app/markdowns/slang.md, app/slang-content/examples/async/async_loop_aggregate.sl, app/slang-content/examples/defaultnav/nav_flow.sl, app/slang-content/examples/divide/division.sl, app/slang-content/examples/divide/master_divider.sl, app/slang-content/examples/hello_world/hello_world.sl, app/slang-content/examples/loops/loops.sl
=> removed unneeded imports

app/index.html, app/scripts/app.js, app/scripts/controllers/community.js, app/scripts/controllers/main.js, app/scripts/controllers/nav.js, app/styles/main.css, app/views/community.html, app/views/getstarted.html, app/views/navbar.html
on the community page, when clicking on the "start now" button in the navigation bar at the bottom of the page, the browser jumped to the bottom of getting started page - fixed. 
also, I added a separate controller to the community page and added the other controllers.
=> controllers updates + bugfix

app/scripts/services/messages.js, app/views/getstarted.html
=> Get started prereq

app/views/workwithcarousle.html
Fixes #155
Carousel speed has changes from 5 seconds to 3.5 seconds.
=> Changed the carousel speed

app/scripts/services/messages.js, app/styles/main.css, app/views/downloadclibox.html
=> get started fixes - version size & executable file name.

app/scripts/controllers/docs.js, app/views/community.html, app/views/footer.html, app/views/getstarted.html, app/views/navbar.html
=> updated links to 0.9

app/scripts/controllers/gettingstarted.js, app/scripts/services/messages.js
=> version links

app/scripts/services/messages.js, app/styles/main.css, app/views/main.html
HI 
I have made some changes in the website text. related to #153 
this is how the title looks like: 
a bit too long in my opinion. what do you think?  
@gfachler
=> test changes

app/views/getstarted.html
Signed-off-by: SamMarkowitz <sam.markowitz@hpe.com>
=> updated to new video

app/views/usecases.html
=> fixed broken use case link

app/views/footer.html
The legal statement was updated.
=> legal statement

app/views/downloadclibox.html
Signed-off-by: Andrei Vasile Truta <andrei-vasile.truta@hpe.com>
=> changing flavor to family in downloadclibox

app/scripts/controllers/gettingstarted.js, app/scripts/services/messages.js, app/views/downloadclibox.html, index.js
Signed-off-by: Andrei Vasile Truta <andrei-vasile.truta@hpe.com>
=> adding cs 1.0.10 references

app/index.html, app/scripts/controllers/docs.js, app/scripts/controllers/gettingstarted.js, app/scripts/services/messages.js, app/views/community.html, app/views/footer.html, app/views/getstartedtodev.html, app/views/getstartedtorun.html, app/views/navbar.html, app/views/suggestworkflow.html, app/views/usecases.html, index.js
=> Update references and other small fixes

app/views/footer.html
Signed-off-by: moldovso <sorin@hpe.com>
=> Fix broken footer links

app/views/usecases.html
Replaced link for OpenStack Health Check
=> Link error

app/scripts/controllers/gettingstarted.js, app/scripts/services/messages.js, app/views/downloadclibox.html, bower.json
=> adding 1.0.23 as latest release
